name: PotatoVerse Dev
port: 7777
hosts:
    - name: '*.localhost'
master_secret: potatosec_b931039b45b7ba56b2997c814a9fa0a5a5756a6cd68ac0d026bd7db02b469226
debug_mode: true
working_dir: /home/bigbird/zhome/code/blue-monads/potato-apps/cimple-form/.pdata
socket_file: /home/bigbird/zhome/code/blue-monads/potato-apps/cimple-form/.pdata/potatoverse.sock
mailer:
    type: stdio
repos:
    - url: https://github.com/blue-monads/store/raw/refs/heads/master
      type: harvester-v1
      slug: Official
      name: Official Potato Field
    - url: https://github.com/blue-monads/store-thirdparty/raw/refs/heads/master
      type: harvester-v1
      slug: ThirdParty
      name: Third Party Potato Field
    - type: dev
      slug: Dev
      name: Development Packages
