name: PotatoVerse Dev
port: 7777
hosts:
    - name: '*.localhost'
master_secret: potatosec_970b12d0289ecc5887c871d13eb617981cbd7cc51e9fc6e6d3b01ac64b40f3b5
debug_mode: true
working_dir: /home/bigbird/zhome/code/blue-monads/potato-apps/cimple-autonoda/.pdata
socket_file: /home/bigbird/zhome/code/blue-monads/potato-apps/cimple-autonoda/.pdata/potatoverse.sock
mailer:
    type: stdio
repos:
    - url: https://github.com/blue-monads/store/raw/refs/heads/master
      type: harvester-v1
      slug: Official
      name: Official Potato Field
    - url: https://github.com/blue-monads/store-thirdparty/raw/refs/heads/master
      type: harvester-v1
      slug: ThirdParty
      name: Third Party Potato Field
    - type: dev
      slug: Dev
      name: Development Packages
